/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Int,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
  'roundupAmount' : IDL.Float64,
});
export const CategoryTotal = IDL.Record({
  'total' : IDL.Float64,
  'category' : IDL.Text,
});
export const MonthlySpending = IDL.Record({
  'month' : IDL.Text,
  'total' : IDL.Float64,
});
export const ExpenseAnalysis = IDL.Record({
  'categoryTotals' : IDL.Vec(CategoryTotal),
  'monthlySpending' : IDL.Vec(MonthlySpending),
  'advice' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const RoundupHistory = IDL.Record({
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const InvestmentWallet = IDL.Record({
  'availableAmount' : IDL.Float64,
  'totalRoundup' : IDL.Float64,
  'investedAmount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [Transaction],
      [],
    ),
  'analyzeExpenses' : IDL.Func([], [ExpenseAnalysis], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvestmentHistory' : IDL.Func([], [IDL.Vec(RoundupHistory)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletSummary' : IDL.Func([], [InvestmentWallet], ['query']),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Int,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
    'roundupAmount' : IDL.Float64,
  });
  const CategoryTotal = IDL.Record({
    'total' : IDL.Float64,
    'category' : IDL.Text,
  });
  const MonthlySpending = IDL.Record({
    'month' : IDL.Text,
    'total' : IDL.Float64,
  });
  const ExpenseAnalysis = IDL.Record({
    'categoryTotals' : IDL.Vec(CategoryTotal),
    'monthlySpending' : IDL.Vec(MonthlySpending),
    'advice' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const RoundupHistory = IDL.Record({
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const InvestmentWallet = IDL.Record({
    'availableAmount' : IDL.Float64,
    'totalRoundup' : IDL.Float64,
    'investedAmount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [Transaction],
        [],
      ),
    'analyzeExpenses' : IDL.Func([], [ExpenseAnalysis], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvestmentHistory' : IDL.Func([], [IDL.Vec(RoundupHistory)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletSummary' : IDL.Func([], [InvestmentWallet], ['query']),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };