/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CategoryTotal { 'total' : number, 'category' : string }
export interface ExpenseAnalysis {
  'categoryTotals' : Array<CategoryTotal>,
  'monthlySpending' : Array<MonthlySpending>,
  'advice' : string,
}
export interface InvestmentWallet {
  'availableAmount' : number,
  'totalRoundup' : number,
  'investedAmount' : number,
}
export interface MonthlySpending { 'month' : string, 'total' : number }
export interface RoundupHistory { 'timestamp' : bigint, 'amount' : number }
export interface Transaction {
  'id' : bigint,
  'userId' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'category' : string,
  'amount' : number,
  'roundupAmount' : number,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[number, string, string], Transaction>,
  'analyzeExpenses' : ActorMethod<[], ExpenseAnalysis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestmentHistory' : ActorMethod<[], Array<RoundupHistory>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletSummary' : ActorMethod<[], InvestmentWallet>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];